version: '3.8'

services:

  mlflow:
    image: python:3.10-slim
    working_dir: /home/yeab/Credit-Risk-Probability-Model
    volumes:
      - ./mlruns:/home/yeab/Credit-Risk-Probability-Model/mlruns
      - ./mlflow.db:/home/yeab/Credit-Risk-Probability-Model/mlflow.db
    command: >
      bash -c "
        pip install --no-cache-dir mlflow pandas scikit-learn &&
        mlflow server \
          --backend-store-uri sqlite:////home/yeab/Credit-Risk-Probability-Model/mlflow.db \
          --default-artifact-root /home/yeab/Credit-Risk-Probability-Model/mlruns \
          --serve-artifacts \
          --host 0.0.0.0 --port 5000
      "
    ports:
      - "5000:5000"

  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    ports:
      - "8000:8000"
    volumes:
      # <-- this must point at the same ./mlruns as above
      - ./mlruns:/home/yeab/Credit-Risk-Probability-Model/mlruns
